### ISSUE TITLE
Failed to make API request if ollama generation takes too long

### ISSUE THREAD

**Issue by vavakado** [efugier/smartcat#22]
This problem occurs if ollama does not generate full answer before timeout.
```
> sc "hello, can you write a cli util in python that tells if it's night or day"
Failed to make API request: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(11434), path: "/api/chat", query: None, fragment: None }, source: TimedOut }
```
For context, everything if working if i use a simpler prompt.

**Comment by efugier** [comment]
Interesting thanks for reporting!
What would be you preferred solution for this? Being able to config a specific timeout value? I can do that.

**Comment by vavakado** [comment]
I think that an option in configs would be more usable for someone with slow hardware, so that they don't have to type additional option every time.

**Comment by efugier** [comment]
That's actually what I meant :slightly_smiling_face: 

I'll get to it as soon as I get some time on my hands!

**Comment by vavakado** [comment]
I probably should close this as the PR #24 was merged
