### ISSUE TITLE
Cosmetic issue with paths on Windows

### ISSUE THREAD

**Issue by johnd0e** [efugier/smartcat#27]
```
API config file not found at "C:\\Users\\adminx\\.config/smartcat/.api_configs.toml", generating one.
```

Should not double backslashes.

P.S.
In general: backslash is canonic path divider on Windows: `"C:\Users\adminx\.config\smartcat\.api_configs.toml"`.
Though in practice in most places it is working even when mixing `\` and `/`: `"C:/Users\adminx/.config\smartcat/.api_configs.toml"`.

**Comment by efugier** [comment]
It is unclear to me whether this is purely a cosmetic issue or if the file was generated at the wrong place in the end.

If it is only cosmetics, this may just be the standard the path is displayed. I am not handling any path stuff myself and rely on the usual Rust libraries to do it for me so I don't really have control over it.

So it's important to me to understand if in the end the correct file was generated or if the extra backslashes found their way in the actual path and got added to the names of the files.

**Comment by johnd0e** [comment]
It is pure cosmetic. The actual created file is `"C:\Users\adminx\.config\smartcat\.api_configs.toml"`.

> this may just be the standard the path is displayed.

I don't think so. It looks like those backslashes displayed escaped, for whatever reason.

**Comment by efugier** [comment]
> It is pure cosmetic.

Alright, that's a relief.

> this may just be the standard the path is displayed
I meant standard from the lib I am using pov!

I looked into it and tried converting to OsString before printing in version [1.7.1](https://github.com/efugier/smartcat/releases/tag/1.7.1), not sure it'll do the trick. Keep me posted!

**Comment by johnd0e** [comment]
As I see the reason is that you are using `{:?}` format.

**Comment by efugier** [comment]
Oh right! [1.7.2](https://github.com/efugier/smartcat/releases/tag/1.7.2) should fix it. Thanks!

**Comment by efugier** [comment]
Please let me know if it worked out :slightly_smiling_face:

**Comment by johnd0e** [comment]
Solved
