### ISSUE TITLE
x11 dependency

### ISSUE THREAD

**Issue by mattephi** [efugier/smartcat#30]
Why does this tool depend on x11 system library? I am not sure what requires this for proper functioning as a cli tool. Like it is not an issue to install libX11-devel on my machine, but this tool requires truly a number of dependencies. Do you think this can be somehow optimized?

**Comment by drewzemke** [comment]
+1, Came here to say that I'm blocked on trying out smartcat on my linux machine because I don't run x11. I tried it on another machine and I so far I'm a huge fan, so I'd love to be able to run it everywhere I work

**Comment by mattephi** [comment]
> I don't run x11

You can try to install devel tools of x11 for now, they do not depend on huge number of packages so it should be fine I guess. On fedora sway spin it was enought to get `libX11-devel`

**Comment by efugier** [comment]
Hey, this likely comes with the `device_query` crate that is used for the voice input feature.

I'm currently hesitating between completely removing it or making it an extra feature that is optional to install.

I thought it would be great for accessibility purposes, but it might be to just remove it for now, I initiated the deprecation process a while ago already I no one asked for it to stay.

**Comment by efugier** [comment]
@mattephi you should no longer have issues after [version 2.0.0](https://github.com/efugier/smartcat/releases/tag/2.0.0). Let me know if it now works for you!
