### ISSUE TITLE
error while loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by DannyBen** [efugier/smartcat#34]
When downloading the linux binary on arch linux.

```shell
$ ./sc
./sc: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory


$ uname -a
Linux hq 6.11.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 22 Oct 2024 18:31:38 +0000 x86_64 GNU/Linux
```

**Comment by d5ve** [comment]
I ran into the same issue on Ubuntu 24.04.1 LTS (which comes with libssl v3) and "fixed" it with the following:

```bash
$ curl -sLO http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
$ sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
```

I found the answers on stackoverflow in a couple of different places. It *looks like* http://nz2.archive.ubuntu.com/ is semi-official, even though downloading openssl over plain http seems like a bad thing to be doing.

I don't know if there is a similar package repo for Arch by the way.

**Comment by DannyBen** [comment]
Thanks. I bumped into this issue with several other rust / go projects. 
This is normally solved without having the users install other libraries.

**Comment by efugier** [comment]
I guess the only thing I can do on my end is to vendor openssl. I tried it and it doubles the binary size so I'm not sure it's the way to go (especially since it to matters to [some users](https://github.com/efugier/smartcat/discussions/31)).

Open to suggestions from someone more knowledgeable than me!

**Comment by DannyBen** [comment]
This is the last place I reported a similar issue and the maintainers fixed it
https://github.com/guilhermeprokisch/see/issues/5

Also Rust. 
This is the diff between the bugged version and the fixed version
https://github.com/guilhermeprokisch/see/compare/v0.2.8..v0.2.9#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R30

Perhaps this is the line responsible for the fix (from Cargo.toml)?
```
reqwest = { version = "0.12.7", features = ["blocking", "native-tls-vendored"] }
```

**Comment by efugier** [comment]
Yes that's vendoring!

Doing it this bumps the binary size to `9.3MB` for everyone; up from `4.4MB` and I'm not sure that's a change I want to make :thinking:
