### ISSUE TITLE
Streaming AI answer

### ISSUE THREAD

**Issue by braunbearded** [efugier/smartcat#45]
Hello, 
first of all great praise for this excellent program. 

Would it also be possible to stream the ai answer? For many applications, this could be problematic (e.g., vim). I think, however, that this could be handled by adding an extra flag. It would be awsome if this could be defined in a configuration file.

I have unfortunately programmed nothing with Rust so far, hence I am currently unable to help here too :/

**Comment by efugier** [comment]
Hey, sorry for the late replay, it's been a busy last couple of days!

I've thought about it a lot and I feel like streaming is not necessary in 99% of use cases, and as you stated it would not work when integrating into other programs.

It would require overhauling the I/O logic, and the only use case I really see is when you're using it straight into the terminal. Usually when doing that you don't expect a huge answer (if I'm going for large stuff, I usually open an editor buffer and have it write in there, but maybe that's just me :man_shrugging:)

So at the current time I don't think I'll start working towards it. 

It may become available later and behavior would be:
- output is terminal → stream
- everything else → no stream

Hope that's not a deal breaker for you, but I think as the focus is on workflow efficiency, that 1% better is currently not worth the hassle of implementing it :slightly_smiling_face:

**Comment by braunbearded** [comment]
Hi, absolutely fair and understandable. I hope you’re enjoying the holidays, and of course, I will continue using smartcat. If the feature gets implemented at some point, please let me know—I’d be happy to help with testing.
