### ISSUE TITLE
Api key from pass

### ISSUE THREAD

**Issue by liborw** [efugier/smartcat#6]
Would it be possible to get api key from pass?

**Comment by efugier** [comment]
What "pass", could you be more specific?

However, the answer will probably be no. There's a dedicated config file for it, you just have to paste it in when running smartcat for the first time.

Smartcat is meant to be a standalone and minimalist cli tool, compliant with the unix philosophy. It won't support integration with any third party program.

**Comment by efugier** [comment]
Closing because no updates.

**Comment by liborw** [comment]
Sorry, I meant [pass](https://www.passwordstore.org/) the standard unix password manager, actually no integration with other tools is nessesary, just an option to specify command to fetch the api key from other tools. I would guess that solution like this is exacly what is meant to be compliant with the unix philosophy. See for example section on  Secrets Management of the [ChatGPT.nvim/README](https://github.com/jackMort/ChatGPT.nvim).

**Comment by efugier** [comment]
Ok so if I get this right implementing `api_key_cmd` would be enough for you right?

**Comment by liborw** [comment]
Yes that's right, actually I have already made test implementation so I can make a pull request, however I do not know whether the quality would be enough.

**Comment by efugier** [comment]
Sorry just saw your last message, I did a quick implementation at #8, needs to be tested though!

**Comment by efugier** [comment]
It should now be supported start at version, `0.6.0`! Feel free to reopen the issue in case of troubles :smiley:
