### ISSUE TITLE
Copilot Support?

### ISSUE THREAD

**Issue by leeola** [efugier/smartcat#7]
Is Github Copilot supported on Smartcat? It seems like not, but this project is tagged with Copilot. 

*edit*: I should add, i am aware Copilot and GPT4 share a lot of functionality, but i was hoping to use my Copilot subscription.

**Comment by efugier** [comment]
Hey sorry it's not supported as of now. It could be in the near future.

The main blocker is that copilot's API is not public. I could take inspiration from project like https://github.com/github/copilot.vim but this is more work for an API that has no guarantee to be stable.

However, I have to say chatgpt's api is very cheap for individual usage. It's pay as you go and for a month it totaled to 1.75$ for me with heavy usage and the latest model: https://openai.com/pricing.

I'm also working on integrating with Mistral.

**Comment by leeola** [comment]
Shouldn't Copilot be removed from this repos tags then? I'm not sure what this repo has to do with Copilot?

**Comment by leeola** [comment]
ah okay lol, kinda confusing imo - but Github took a basic word :shrug:

**Comment by efugier** [comment]
Yes ahah, I actually started this project because copilot was not available for the editor I use (helix), and in my current workflow it kinda holds the same role!

**Comment by leeola** [comment]
Out of curiosity, would you be interested in generalizing the underlying communication, if support for Copilot was added?

**Comment by efugier** [comment]
I'm not sure what you mean by that 🤔

**Comment by leeola** [comment]
Hah, think i was short on coffee and missed a word. Generalizing the underlying LLM APIs (in this case, generalizing OpenAPI IO), if it isn't already, as to allow for alternate impls of LLMs/etc.

Might be some overlapping space with other similar libraries, too. Eg core libs of [llmvm](https://github.com/DJAndries/llmvm/) /etc generalize this i believe?

**Comment by efugier** [comment]
Smartcat is supposed to remain a minimal tool compliant with the unix philosophy. It's pretty unlikely for the project to get abstracted and separated in several lib. However, it's built with the requirement of supporting multiple llm providers in mind.

For now, the only other supported provider is Mistral AI. 

As it is almost the same schema as openai additional code was requiered but basically there's kind of an [adapter pattern](https://github.com/efugier/smartcat/blob/80e4e53980269dbd65d92f7bbd4e1dc0ca9b2bbb/src/request.rs#L47-L57) from the generic prompt schema of `smartcat` [to the target API for the call](https://github.com/efugier/smartcat/blob/80e4e53980269dbd65d92f7bbd4e1dc0ca9b2bbb/src/request.rs#L77-L79).

Implementing new ones should be super fast if the API is well documented :slightly_smiling_face:
